const main = async () => {};
main().catch((error) => {
  console.error(error);
  process.exit(-1);
});
